"""Order and execution cost models."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


Side = Literal["BUY", "SELL"]


@dataclass(frozen=True)
class Order:
    """Market order generated by the backtesting engine."""

    date: object
    ticker: str
    side: Side
    quantity: int
    reference_price: float


@dataclass(frozen=True)
class Fill:
    """Executed order with slippage and explicit transaction cost."""

    date: object
    ticker: str
    side: Side
    quantity: int
    reference_price: float
    executed_price: float
    notional: float
    transaction_cost: float
    slippage_cost: float


@dataclass(frozen=True)
class ExecutionModel:
    """Simple market-order execution model in basis points."""

    transaction_cost_bps: float = 5.0
    slippage_bps: float = 2.0

    def execute(self, order: Order) -> Fill:
        """Apply side-dependent slippage and proportional transaction cost."""

        if order.quantity <= 0:
            raise ValueError("quantity must be positive")
        if order.reference_price <= 0:
            raise ValueError("reference_price must be positive")

        side_multiplier = 1.0 if order.side == "BUY" else -1.0
        slippage_rate = self.slippage_bps / 10_000
        executed_price = order.reference_price * (1 + side_multiplier * slippage_rate)
        notional = executed_price * order.quantity
        transaction_cost = abs(notional) * self.transaction_cost_bps / 10_000
        slippage_cost = abs(executed_price - order.reference_price) * order.quantity
        return Fill(
            date=order.date,
            ticker=order.ticker,
            side=order.side,
            quantity=order.quantity,
            reference_price=order.reference_price,
            executed_price=executed_price,
            notional=notional,
            transaction_cost=transaction_cost,
            slippage_cost=slippage_cost,
        )

    def estimated_cash_required(self, quantity: int, price: float) -> float:
        """Estimate cash needed for a buy order."""

        gross = price * (1 + self.slippage_bps / 10_000) * quantity
        return gross * (1 + self.transaction_cost_bps / 10_000)
